name: Deploy

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

jobs:
  publish-images:
    name: Publish Docker image
    runs-on: ubuntu-22.04

    outputs:
      env: ${{ steps.extracted-output.outputs.ENV }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set Development env
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          echo "ENV=dev" >> $GITHUB_ENV
          mv apps/${{ inputs.context }}/.env.dev apps/${{ inputs.context }}/.env

      - name: Set Production env
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "ENV=prod" >> $GITHUB_ENV
          mv apps/${{ inputs.context }}/.env.prod apps/${{ inputs.context }}/.env

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cpe-kmutt-student/bangmod-hackathon-2023-${{ inputs.context }}

      - name: Extract output
        id: extracted-output
        run: |
          echo "::set-output name=ENV::${{ env.ENV }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/${{ inputs.context }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    name: Deploy
    needs: [publish-images]
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ${{ secrets.SSH_CWD }}
            export ENV=${{ needs.publish-images.outputs.env }}
            export SERVICE="$ENV-${{ inputs.context }}"
            echo "Pulling $SERVICE"
            docker compose pull $SERVICE
            echo "Deploying $SERVICE"
            docker compose up -d $IMAGE
            docker image prune
