name: Add issue to GitHub Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/cpe-kmutt-student/projects/1/
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
